### ISSUE TITLE
Exposing statements (`Vec<Stmt>`)

### ISSUE THREAD

**Issue by chinedufn** [connorskees/grass#50]
Hey!

I'm considering using `grass` for a project and would like to get access to some information that grass does not currently expose.

I saw in the README:

> It offers a very limited API, currently exposing only 2 functions.

So if what I'm asking for goes against the project's goals that's totally fine and I can just fork.

## Problem

I write my HTML in Rust and would like to prevent typos when dealing with CSS. For example:

```rust
// BAD: I don't want to do this
let _ = html! { <div class="cool-class"></div> };

// GOOD: I want to do this
let _ = html! { <div class=MyClassEnum::CoolClass></div>
```

In order to do this, my build script needs to be able to know every class that is defined in the sass so that it can generate the enum.

## Where grass comes in

It looks like grass has a `Stmt` type which contains all of the information that I would need.

i.e. `SimpleSelector::Id` `SimpleSelector::Class` etc.

---

One way to enable this would be to expose a new function:

```rust
pub fn stmts_from_path (path: &str, options: &Options) -> Result<Vec<Stmt>> {
    todo!()
}
```

This would mean that I would have to not only run the parser once to get my CSS String, but also another time to get my statements.

## In Closing

I've suggested one potential path forwards, but I'm pretty open to anything that allows me to do what I want to do.

I'm also happy to just find a new approach (i.e. fork, regex, something else) to get the information that I want if supporting this use case doesn't fit into grass' vision.

So, to me it just comes down to 

## EDIT

**EDIT:** Exposing statements would also be generally useful for other tooling. For example, a linter that enforces a naming schema.

**Comment by connorskees** [comment]
Hello,

Thanks for the feature request! I'll keep this usecase in mind in the future -- I would like to someday expose a lot of the internals of this library. I would really like to see a post-CSS-like API implemented on top of this library.

Unfortunately, for right now I can't make that struct public. It is subject to too much change. In addition, I don't think it would be exactly what you want. Sass selectors can get quite complex. If you want only simple selectors, you would have to access the selectors after parent selectors (`&`) are resolved, because it is feasible (and quite common) for a selector like `&a` => `ba` to exist. If you want anything larger than simple selectors (compound, complex), you would have to access the selectors after extension.

My personal suggestion would be to eat the cost of double-parsing, using a library like https://github.com/servo/servo/tree/master/components/style or similar to parse the emitted CSS.

Alternatively, you could modify the code used to emit CSS (https://github.com/connorskees/grass/blob/master/src/output.rs#L174), which handles extension and has already had parent selectors resolved. There may be some complexity in handling `@media` queries and other `@-rules`, but it should be closer to what you're looking for.

**Comment by connorskees** [comment]
Unrelated to this feature, converting the selector `.cool-class` to `MyClassEnum::CoolClass` seems a bit dubious as it's possible for a class `.coolClass` to exist as well, which would presumably be emitted with the same name. I'm not really sure of a good solution to that problem, bar changing the former example to something like `MyClassEnum::CoolHyphenClass` or changing the API completely to be stringly typed, and checked against a list of selectors at compile time through a proc macro. Would be interested to know if you have found a better way around those name conflicts -- sounds like an interesting problem.

**Comment by chinedufn** [comment]
My personal solution here stems from me not wanting the name `.coolClass` to even be possible in the first place. 

So, I', just going to fail if you use capital letters (as well as if you violate any other lints).

**Comment by connorskees** [comment]
Ah, that makes sense. Though, what about `.coolclass` and `.cool-class`? Same conflict, though potentially less likely

**Comment by chinedufn** [comment]
Yeah for sure it's an assume. But I don't foresee anything like this coming up that won't be easily solved at build time.

I.e. before actually generating the `MyClassEnum` I'll probably have some sort of `HashMap<LowercaseString, Vec<Occurrence>>`  (at least conceptually.. might not look like that when I really implement it). 

And so if the map had `<coolclass, vec![occurence1, occurence2]>` in it I'd print an error and fail the build.

**Comment by chinedufn** [comment]
Ah didn't even see this comment

https://github.com/connorskees/grass/issues/50#issuecomment-894815629

Sweet, thanks for the consideration!!
