### ISSUE TITLE
Upgrade clap to remove dependency on unmaintained atty crate

### ISSUE THREAD

**Issue by esimkowitz** [connorskees/grass#84]
I have been getting component governance alerts for Grass due to its nested dependency on atty, which has been unmaintained for a few years now and has some compatibility issues with Windows. Your nested dependency on atty comes from clap, though they've moved away from atty as of last year (see https://github.com/clap-rs/clap/pull/4249).

Here's a link to the advisory in the GitHub Security Advisory Database: https://github.com/advisories/GHSA-g98v-hv3f-hcfr

**Comment by connorskees** [comment]
I've been putting off updating clap for a while. I agree the warning is quite annoying. I've updated the clap version in `master`, and this change should be released to crates.io quite soon as `0.13.1`. I'll note that the MSRV of this crate has to increase to 1.64.0 in order to work with the newest version of clap. Unfortunately the change you linked was not backported to `3.x.x`.

**Comment by connorskees** [comment]
This change has been released to crates.io as [`0.13.1`](https://crates.io/crates/grass/0.13.1). Thanks for the bug report!
