### ISSUE TITLE
Make `include!` macro accept an $expr instead of $literal

### ISSUE THREAD

**Issue by hirschenberger** [connorskees/grass#99]
I have a project that is used as a git submodule in another project.

I try to `include!` my sass file like this to make it work for nested projects like this: 

```rust
static CSS: &str = grass::include!(concat!(std::env!("CARGO_MANIFEST_DIR"), "/assets/mystyle.sass"));
```

Unfortunatly this does not work, as `grass::include!`only acceps a `$literal`. It seems this contraint can be relaxed, as e.g. `std::include_str!` also accepts an `$expr`.

**Comment by connorskees** [comment]
hmmm i like this idea, but i'm not sure how possible it is. `include_str!` and `concat!` accept expressions, but they're compiler builtins. do you know of some way to parse something like `concat!(std::env!("CARGO_MANIFEST_DIR"), "/assets/mystyle.sass")` into a string in a macro without writing a full expression parser? 

in theory we could make the macro accept a list of string literals and concatenate them ourselves, but that doesn't solve the problem of `env!`

the workaround for this problem is generally to just write a build script, which shouldn't be too bad in this case

**Comment by hirschenberger** [comment]
`include` is a regular declarative macro, when another macro is passed as a paramter to it, the inner macros is resolved first. So shouldn't `include` just get a string slice?

**Comment by connorskees** [comment]
ah, the implementation actually just calls out to a proc macro, which is how the sass gets compiled at compile-time

https://github.com/connorskees/grass/blob/e0bb9e2eabfc3a58e42b03089cd7b22c68d09d0b/crates/lib/src/lib.rs#L94-L98

https://github.com/connorskees/grass/blob/e0bb9e2eabfc3a58e42b03089cd7b22c68d09d0b/crates/include_sass/src/lib.rs#L89-L90

**Comment by hirschenberger** [comment]
Sorry, I don't get it. Can't `include_sass` alternatively accept a string slice?

**Comment by connorskees** [comment]
i'm not totally sure what you mean by accept a string slice. i think you mean a string which is not a literal? this macro can't accept arbitrary expressions, as doing so would require evaluating the rust AST inside of the macro

builtin macros are a bit different because they can construct literal strings, though still the tokens that the proc macro is given aren't that of a literal string. `concat!(..)` isn't a string literal -- it is an identifier, a bang, an open paren, and so on. in order to accept a string, the inner macros would have to be expanded in some way. there are a few ways to do this, but they are generally not that robust. one option is to use [`expand_expr`](https://doc.rust-lang.org/beta/proc_macro/struct.TokenStream.html#method.expand_expr), which is only supported on nightly

with some looking, i did find [with_builtin_macros](https://docs.rs/with_builtin_macros/latest/with_builtin_macros/index.html), which will expand builtin macros for you on stable. i was able to successfully implement the behavior you're looking for. this isn't something that this crate could adopt, but is something end users can use

<img width="494" alt="Captura de pantalla 2024-08-06 a la(s) 9 22 55 a m" src="https://github.com/user-attachments/assets/6ed35a53-6da1-4acb-9fbf-50aa0c2ec8b8">

**Comment by connorskees** [comment]
Closing this issue out, as I think builtin macro expansion is outside the scope of this crate, and  [with_builtin_macros](https://docs.rs/with_builtin_macros/latest/with_builtin_macros/index.html) seems to implement this quite well. Please feel free to reopen if you think there's a way to support macro expansion that I'm missing
